language: python
dist: xenial

python:
  - "2.7"

install:
  - pip install .
  - pip install codecov
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt

# run tests
script:
  - coverage run -m pytest -vv

after_success:
  - coverage report --show-missing

notifications:
  email: false
