language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install .
  - pip install coveralls --use-mirrors
  - pip install -r requirements.txt --use-mirrors

after_success:
  - coveralls

# run tests
script: nosetests
