language: python
python:
  - "2.7"

install:
  - pip install .
  - pip install coveralls
  - pip install -r requirements.txt

after_success:
  - coveralls

# run tests
script: nosetests --with-coverage --cover-package=nzbget
